### ISSUE TITLE
Klimamonitor: DELMÅL 5: Elektrificering af personbiler

### ISSUE THREAD

**Issue by jmk-randers** [Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter#10]
## SENEST I 2030: 25% af alle personbiler, der er indregistreret i Randers Kommune som geografi, er el- eller brintbiler (ikke hybrid)

Reduktion af klimagasser (i forhold til 2018): 32.500 ton/år

### Kategori:
Transport

### KPI:
Procentdel af indregistrerede biler

### Mål:
25% inden 2030

### Datakilde:
Forventet datakilde:
https://www.statistikbanken.dk/bil54

Dataejer: ?

**Comment by kf-randers** [comment]
Done
