### ISSUE TITLE
Adgang til NPM moduler?

### ISSUE THREAD

**Issue by st-randers** [Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter#106]
Efter sync i argo, går tjenesten i stå ved download af dayjs npm modul.
![image](https://github.com/Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter/assets/115066094/42df4aa1-7847-45d6-8871-9363c9fe175b)

Skal der åbnes for adgangen i netpol?

Vi kan ikke finde ud af at lave log overvågning i Grafana, så vi var nødt til at kigge ind i Argo. Kan I hjælpe os med det? ^^ 
https://grafana.t0.hosting.kitkube.dk/d/uJAUA3uVz/klima-logs?orgId=125&from=now-1h&to=now

**Comment by st-randers** [comment]
Den kom videre efter noget tid, og det ser umiddelbart ud til at virke som det skal. 

Den sidste del af loggen var dog meget forsinket, både i Argo og i Grafana.

**Comment by jmk-randers** [comment]
@bork91: Vi kører (som du ved) npm install https://github.com/Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter/blob/f0589c80e3c0075ab4b17cf7513c14d25e03cad3/node-red/Dockerfile#L6 når imaget bygges og vores package.json indeholder dayjs https://github.com/Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter/blob/f0589c80e3c0075ab4b17cf7513c14d25e03cad3/node-red/package.json#L32

Så det burde virke, er det blot fordi vi skal være mere tålmodige efter et deploy?

Hvor hurtigt kan vi forvente at se log data inde i Grafana efter et deploy?

**Comment by jmk-randers** [comment]
@st-randers: var det "bare" en forsinkelse? Bliver der skrevet nye data for OpenData kilderne??

**Comment by bork91** [comment]
Det tyder på at opstart af applikationen tager noget tid.

Log er i Grafana indenfor nogle sekunder efter de er blevet skrevet til stdout af containeren.

**Comment by jmk-randers** [comment]
@st-randers : Du havde nogle inputs omkring det man kunne se i loggen i Grafana? Det var ikke det hele det var tilgængeligt, eller hvordan var det?

**Comment by st-randers** [comment]
@bork91 Hvor længe kan vi forvente at det tager at starte / bygge applikationen? Fra sync til at applikationen er kørt færdig? Kan vi overvåde det i realtid, nemmere end argo logs?

**Comment by bork91** [comment]
@st-randers jeg kan ikke sige noget hvor for længe en applikation tager om at starte. Det afhænger af hvor meget den skal gøre før den melder klar på dens readinessProbe. Der er også stor forskel på hvilket sprog applikationen er skrevet i samt hvor mange dependencies der skal loades under opstart.

Vil du måle hvor længe et job tager om at køre i K8S eller vil du gerne have tiden fra en container bliver startet til den melder klar på readinessProbe?

Normalt har start op tid ikke den store betydning af der stadig køre den gamle instance af applikationen indtil den nye melder klar på readinessProbe.

**Comment by jmk-randers** [comment]
@st-randers , @bork91:

Jeg tror dether issue udvikler sig i retning af at vi gerne vil kunne overvåge vores applikationer på et Grafana dashboard, lære hvordan vi sætter et op med logs og hvad vi kan forvente af svartider o.s.v.  Det er mere generelt og kommer forhåbentligt når vi får Overvågning med Grafana implementeret ordentligt...
