### ISSUE TITLE
Align / recreate database in test

### ISSUE THREAD

**Issue by st-randers** [Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter#108]
Forbrug flow -> unknown column "TotalCon"
![image](https://github.com/Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter/assets/115066094/cfa84b89-312a-4710-b6f2-803bb8b8e688)

BIL54 duplicate entry for key Måned -> fejl i parsing?
![image](https://github.com/Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter/assets/115066094/bd1eb875-f56b-4784-8d88-84bfd1e3a621)

```[tasklist]
### Tasks
- [ ] Forbrug flow fix
- [ ] BIL54 flow fix
```

**Comment by jmk-randers** [comment]
TotalCon er en af de omdøbte kolonnenavne, MEN hvis vi laver en "vi deployer helt fra start" metode der kører via "trigger once when deployed" og genskaber databasen der ud fra den dynamiske dataskabelon, så vil det køre af sig selv.

Det betyder i nuværende implementering at vi ikke kan gemme historiske data, der afviger fra dem som står i datakilderne.

Skulle det behov opstå, kan vi kigge henimod en løsning der versionerer eller daterer tabelnavnet, så den gamle tabel bliver liggende og der oprettes en helt ny tabel ved siden af med en ny version og/eller et timestamp for oprettelsen f.eks..
