### ISSUE TITLE
superset.prototypes adgang til "Camilla Oxholm Sørensen" <Camilla.Oxholm.Sorensen@randers.dk>

### ISSUE THREAD

**Issue by jmk-randers** [Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter#120]
Hej, kan i tilføje "Camilla Oxholm Sørensen" <Camilla.Oxholm.Sorensen@randers.dk> til superset.prototypes i Keycloak. 

Hun skal have "Udvikler" rollen på SuperSet klienten i KeyCloak, som gerne skulle mappe til "Gamma og sql_lab" rollerne i Superset (men jeg kan ikke logge ind i KeyCloak og tjekke)

@CamillaOS - du kan følge med her

**Comment by bork91** [comment]
Hej @jmk-randers  og @CamillaOS 

Jeg har nu tilføjet rollerne Gamma og sql_lab til Camillas bruger, så nu skulle hun gerne kunne logge ind i superset og have disse roller.

**Comment by CamillaOS** [comment]
Hej - jeg har adgang til superset.prototypes, men ikke til nogen af datasættene.

**Comment by st-randers** [comment]
@CamillaOS Jeg kunne se du ikke havde rollen "sql_lab" som ellers var meningen, så den har jeg tildelt dig nu. 
Kan du se datasæt nu?

**Comment by CamillaOS** [comment]
Nej, jeg kan stadig ikke se datasættene.

**Comment by st-randers** [comment]
@CamillaOS Nu skulle du gerne kunne. Prøv igen =)

**Comment by CamillaOS** [comment]
![image](https://github.com/Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter/assets/134509376/ada67cb7-d63d-4899-9264-fc487435f26b)
Desværre. Det ser ligeså blankt ud som før.

**Comment by st-randers** [comment]
@bork91 Kan du hjælpe? Jeg har tildelt "can read on datasets" m.fl. til rollen "sql_lab", men Camilla kan stadig ikke se datasets.

**Comment by bork91** [comment]
@st-randers Jeg ser på det, det ser ud til at superset kun tage en rolle med ind fra keycloak. Det er jeg ved at løse :)

**Comment by bork91** [comment]
@st-randers så er det løst, problemet var at flere roller ikke virkede. Det gør det nu. 
Til info roller skal tildeles i Keycloak. Som det er nu er det kun KIT der kan dette. 

@CamillaOS nu har du adgang til datasættene :)

**Comment by CamillaOS** [comment]
Fantastisk :) Tak for hjælpen
