### ISSUE TITLE
Dansk nummerformattering på alle charts

### ISSUE THREAD

**Issue by kf-randers** [Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter#121]
Alle charts på Klimamonitoren skal formateres til dansk standard inden de lægges på dashboarded. 

Eksempel: 
`FORMAT(vomgasser_CH4, 2, 'da_DK') as vomgasser_CH4`

Ovenstående virker udmærket i SQL Lab, men det virker ikke i Superset

**Comment by st-randers** [comment]
Mulig løsning er at ændre locale konfigurationen i Superset iflg.: https://www.appsloveworld.com/d3js/100/14/customise-the-number-format-in-apache-superset

**Comment by kf-randers** [comment]
@st-randers: Skal vi planlægge en test af denne løsning en dag? Vi skal vel "blot" rette i vores Superset applikation (dev-superset) og re-deploye den?

**Comment by kf-randers** [comment]
Foreløbigt er dette problem parkeret, da det kræver vi vedligeholder vores eget Superset.

**Comment by st-randers** [comment]
> Foreløbigt er dette problem parkeret, da det kræver vi vedligeholder vores eget Superset.

Vi forsøger lige med en anden løsning før vi parkerer den: https://github.com/Randers-Kommune-Digitalisering/k8s-issues/issues/34

**Comment by kf-randers** [comment]
Done
