### ISSUE TITLE
SuperSet / MariaDB errors

### ISSUE THREAD

**Issue by st-randers** [Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter#130]
Jeg har i dag, og i går, oplevet nogle fejl i Superset på prototypes. 

Jeg har oplevet både fejl 400 og 500 ved forsøg på at oprette nye datasæt (den kan ikke læse schema fra database).
![image](https://github.com/Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter/assets/115066094/0d0a6502-1d20-47f7-949a-f1f43aa598ad)

Jeg oplever pt. også følgende fejl på MariaDB gennem Superset.
![image](https://github.com/Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter/assets/115066094/4b259945-194a-4704-8798-25aa77139682)

Jeg har lavet en ændring til min [docker-compose.yml](https://github.com/Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter/blob/main/docker-compose.yml) hvor jeg har tilføjet linjen "command" under db imaget. 
Kan I sørge for at det også bliver en del af helm chartet på prototypes? Dene løser 'too many connections' ved at ændre timeout til 60 sekunder.

**Comment by bork91** [comment]
Umiddelbart så skal der nok ses på om der mangler index i databasen eller andet som kan optimere brugen af MariaDB. Too many connections i et lille setup som dette tyder på at der er slow queries. Måske pga. manglede index.

Skal vi dykke ned i hvilke index der bør laves eller er det noget i selv kan klare? Det bedste er at dem som bruger databasen også laver index, da de ved hvad der bliver søgt på :)

**Comment by bork91** [comment]
Det kan også være der er brug for en connection pool, oprettes der er ny database forbindelse for hver kald til databasen eller laver node-red en DB pool?

**Comment by st-randers** [comment]
@bork91 Too many connection er et resultat af at alle connections bliver holdt åbent i 8 timer som default. Der oprettes nye forbindelse ved hver request. Derfor skal denne ændring implementeres fra mit codespace over i prototypes.

Ift. index ved jeg ikke, jeg vender den lige med Jan.

**Comment by st-randers** [comment]
@bork91 Vi har mulighed for at pool connections, men uanset hvad skal én forbindelse ikke være åben i 8 timer. Så det må du meget gerne ændre til de 60 sekunder på prototypes, som jeg har gjort i docker-compose.

Vores queries er ikke langsomme, men sker forholdvis ofte pga. IoT device updates. Vi kigger på at skifte implementationen til pooling i stedet.

**Comment by bork91** [comment]
@st-randers så er det sat.
![image](https://github.com/Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter/assets/15649322/7eb2f5e7-fee3-4768-b2cc-342c32de6d76)

https://github.com/Randers-Kommune-Digitalisering/kithosting-randers-kommune-apps/commit/e25f9c3a69da9d46af8089011ecb223ff28e2ac2

**Comment by st-randers** [comment]
@bork91 Perfekt, mange tak :)

Løser det mine problemer ift. HTTP 400 / 500?
Jeg har jeg ingen problemer pt.

**Comment by bork91** [comment]
@st-randers det tro jeg. Kan se at superset har givet 400 og 500 som HTTP status lige efter den har giver en SQL fejl med Too many connection

**Comment by st-randers** [comment]
@bork91 Det lyder super, jeg lukker issuet!
