### ISSUE TITLE
Error: ER_BAD_FIELD_ERROR: Unknown column 'aarstal' in 'field list'

### ISSUE THREAD

**Issue by ghost** [Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter#135]
@jmk-randers @st-randers 
Det virker stadig ikke. Har I mulighed for at kigge på det.
Jeg får fejlen: Error: ER_BAD_FIELD_ERROR: Unknown column 'aarstal' in 'field list'

_Originally posted by @CamillaOS in https://github.com/Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter/issues/73#issuecomment-1689499082_

**Comment by jmk-randers** [comment]
Changes comitted: https://github.com/Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter/commit/0c1fb5b6eb5058b035c088671984f372dba9b578
