### ISSUE TITLE
Fejl i overførsel af brændstofdata til Superset.

### ISSUE THREAD

**Issue by CamillaOS** [Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter#147]
Hej Søren
Brændstofdata, som indtil for nylig er blevet vist helt rigtigt i Superset, bliver nu pludselig ikke overført fra OpenData, som det skal. Kan du hjælpe mig med at finde ud af, hvad problemet er?
Data hører til indikator 22.1: Benzin- og dieselforbrug (TJ)

![Image](https://user-images.githubusercontent.com/134509376/268925757-cfd11676-c427-42a3-af77-721c6d0809ca.png)

**Comment by st-randers** [comment]
@CamillaOS Jeg kigger på det.

**Comment by kf-randers** [comment]
@st-randers, @CamillaOS: 

Det ser ud til at have løst sig selv... Det virker i hvert fald nu. Jeg rodede med Node-RED tidligere. Det var måske derfor.
