### ISSUE TITLE
HTML Sanitazion i Superset

### ISSUE THREAD

**Issue by kf-randers** [Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter#159]
@st-randers og @rak-randers 

Vi anvender Handlebars charts i Klimamonitoren til at dokumentere opdatering af datasæt. Det er muligt at style disse charts med css, men det kræver enten at HTML Sanitazion er enabled. Alternativt skal der indskrives nogle undtagelser i HTML_SANITIZATION_SCHEMA_EXTENSIONS i Superset. Er det muligt?

Problemstillingen er beskrevet her: https://preset.io/blog/superset-patch-release/#handlebars-chart-configuration

**Comment by st-randers** [comment]
@kf-randers Er dette stadig et problem i v3 ?

**Comment by kf-randers** [comment]
Jeg tror ikke dette er et issue længere
