### ISSUE TITLE
Størrelse på dahsboards

### ISSUE THREAD

**Issue by kf-randers** [Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter#173]
Superset melder at Dashboardet Klimamonitor har nået sin maksimale størrelse og der derved ikke kan tilføjes flere charts. Det burde dog kunne ændres i opsætningen ved at ændre parameteren: 

`SUPERSET_DASHBOARD_POSITION_DATA_LIMIT = 65535`

Med docker skal det muligvis placeres her i stedet:
`./docker/pythonpath_dev/superset_config_docker.py`

Se: 
https://github.com/apache/superset/tree/master/docker

**Comment by st-randers** [comment]
Jeg har øget størrelsen på dashboards til det dobbelte.

MariaDB's TEXT column length er = 65535 characters, og SUPERSET_DASHBOARD_POSITION_DATA_LIMIT nu er sat til = 131070 bytes (65535 characters UTF-8 encoding = 131,070 bytes), dvs. vi har nu ramt max størrelse.
