### ISSUE TITLE
Antal cykelrejser i gennemsnit over Randers Fjord

### ISSUE THREAD

**Issue by jmk-randers** [Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter#18]
Datakilde: https://www.opendata.dk/randers-kommune/antal-krydsende-cyklister-over-randers-fjord

Dataconnector til OpenData er kodet og klar til at bliver forbundet til datakilden.

Skal indikator tallet være baseret på "MDT - dagligt gennemsnit for måneden"?

**Comment by jmk-randers** [comment]
Opendata Connector #39 der håndterer flere filer og tager højde for datafilens alder baseret på metadata er testet på datasettet. 

Datasættet indeholder specialtegn i kolonnenavnene, så #40 datalake oprettelse fejler

@Lisbeth-8752, @kf-randers : Kan vi stille krav i guiden om at man ikke må anvende specialtegn i kolonnerne (som f.eks paranteser) eller skal vi prøve at lave en masse kode der renser alle specialtegn væk fra kolonnenavnene?

**Comment by Lisbeth-8752** [comment]
Godmorgen😊
Det tænker jeg godt vi kan- stille krav guiden.
Mvh
Lisbeth

Sendt fra min iPhone

Den 26. apr. 2023 kl. 07.28 skrev Jan Kjerbye ***@***.***>:

﻿

Opendata Connector #39<https://github.com/Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter/pull/39> der håndterer flere filer og tager højde for datafilens alder baseret på metadata er testet på datasettet.

Datasættet indeholder specialtegn i kolonnenavnene, så #40<https://github.com/Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter/issues/40> datalake oprettelse fejler

@Lisbeth-8752<https://github.com/Lisbeth-8752>, @kf-randers<https://github.com/kf-randers> : Kan vi stille krav i guiden om at man ikke må anvende specialtegn i kolonnerne (som f.eks paranteser) eller skal vi prøve at lave en masse kode der renser alle specialtegn væk fra kolonnenavnene?

**Comment by jmk-randers** [comment]
@kf-randers Er der en opgave på at kontakte dataejer?

**Comment by jmk-randers** [comment]
@kf-randers 

Efter vi har været tvunget til at lave kolonneomsætninger i forbindelse med brændstofdata opgaven har vi lavet OpenData connectoren generisk og den fjerner specialtegn. Det betyder at dette datasæt nu kommer ind korrekt uden at fejle som beskrevet i #40 

Tabellen hedder opendata_antal_krydsende_cyklister_over_randers_fjord  og er tilgængelig tilat lave datasets ud fra i superset.prototypes.randers.dk
