### ISSUE TITLE
Metadata på data fra Danmarks Statistik

### ISSUE THREAD

**Issue by kf-randers** [Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter#31]
Der findes metadata fra Danmarks Statistik for hver tidsserie. Vi kan bruge det til at trigge nye requests, lave dokumentation m.m.. 

Kan vi bygge det ind som funktionalitet når vi trækker data fra statbank.dk?

Eksempel
<a href="placeholder.com" target="_blank">https://api.statbank.dk/v1/data/bil54</a>
<a href="placeholder.com" target="_blank">https://api.statbank.dk/v1/tableinfo/bil54</a>

**Comment by jmk-randers** [comment]
Officielle docs: 
https://www.dst.dk/da/Statistik/brug-statistikken/muligheder-i-statistikbanken/api#metadataogdata

**Comment by jmk-randers** [comment]
@kf-randers: Hvad er første mål med at anvende metadata? Skal det være at trække udgivelses datoen ind i et fast interval og kun trække data hvis der er en udgivelses dato der er nyere end seneste række i DB?
Andre ideer?
Lad os få opgaven brudt lidt ned i mindre bidder.

**Comment by jmk-randers** [comment]
Kernefunktionalitet introduceret i #93
