### ISSUE TITLE
Byg af ny SuperSet container med prophet support

### ISSUE THREAD

**Issue by jmk-randers** [Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter#32]
For at kunne levere forecasting i SuperSet skal der bygges en ny container med de rette requirements.

**Comment by jmk-randers** [comment]
SuperSet containeren bygges som en std. python container -> https://docs.docker.com/language/python/build-images/

https://github.com/apache/superset/tree/master/docker

Der skal bygges et image ud fra en requirements.txt i repoet og buildet kører så en standard `RUN pip3 install -r requirements.txt`

**Comment by bork91** [comment]
Det er nu tilføjet SuperSet i test via config af helm chart.

**Comment by bork91** [comment]
@jmk-randers Vil du teste om det virker?
