### ISSUE TITLE
Manglende opdatering af data fra motorregisteret

### ISSUE THREAD

**Issue by kf-randers** [Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter#45]
Data i prototypes fra BIL54 er ikke opdateret siden marts. @jmk-randers kan du se hvad der fejler?

**Comment by jmk-randers** [comment]
Fejlen identificeret, begynder de rettelser der skal til

**Comment by jmk-randers** [comment]
Det viser sig ikke at være en fejl, men en misforståele omkring udgivelses datoer på datasættet.

En konservativ analyse viser at den 3. mandag i hver måned sandsynligvis vil kunne ramme alle udgivelserne, mod en lille tradeoff på 3-5 dages forsinkelse mellem udgivelse og data på dashboard. Den statiske schedule er nu sat således:
![image](https://github.com/Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter/assets/80261692/54f59e8c-e151-44b6-a6ce-63f29d0a2199)

**Comment by jmk-randers** [comment]
Hvis scheduling skal forbedres yderligere skal der laves en mere dynamisk scheduler der tjekker metadata f.eks i et dagsinterval. Der er oprettet en branch #31 til dette, men mere realtime data er ikke prioteret p.t.

**Comment by jmk-randers** [comment]
@kf-randers: Ved test af ny forbedret scheduler kode kommer der stadig ikke noget data fra måned 05 fra statistikbankens API, det seneste er fra 04. 
Dette kan bekræftes ved manuel verificering via https://api.statbank.dk/console#data i en browser.

**Comment by jmk-randers** [comment]
Ved gennemgang af datakilde info ser det ud til at alle opdateringer på DST er en måned forskudt, så der kommer først data for 05 måneden efter.

https://www.statbank.dk/statbank5a/SelectVarVal/define.asp?MainTable=BIL54&PLanguage=0&Tabstrip=INFO&PXSId=0&SessID=420871727&FF=20&tfrequency=12

Med den nye konservative schedule trækkes disse tal og vises på dashboardet mandag d. 19 juni. Så er vi 100% sikre på at få data ned, selvom DST er forsinket.

Som nævnt er den eneste måde at sikre at vi får data ned tættere på DSTs opdateringsdato at lave en dynamisk shceduler baseret på metadata.

**Comment by kf-randers** [comment]
@jmk-randers Tjek. Vi kan overveje det, når vi når til [#31](https://github.com/Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter/issues/31). Den er først på [Release af Klimamonitor v. 1.0](https://github.com/Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter/milestone/3)
