### ISSUE TITLE
Dataformat for "Måned" not ISO8601 - datalake generator fails

### ISSUE THREAD

**Issue by jmk-randers** [Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter#53]
For at datalake generatoren kan genkende "Måned" feltet som en DATE skal det formatteres som ISO8601.. Lige nu sættes den til FLOAT af generatoren.

Kan måske fikses ved at ændre på data dynamisk, eller ved at dataejeren følger guiden.

@kf-randers: Har du nogen holdninger til det?

**Comment by jmk-randers** [comment]
Work is done in #50

**Comment by jmk-randers** [comment]
@st-randers: er denne ikke fikset med ændringerne i #50 ?

**Comment by st-randers** [comment]
Jo, det er formateret som DATE format nu (YYYY-MM-DD) i MariaDB (parsed med dayjs)
