### ISSUE TITLE
Adgang til data i SQL Lab i Superset fejler

### ISSUE THREAD

**Issue by kf-randers** [Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter#58]
Se billede

![Image](https://github.com/Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter/assets/122357806/25a1a937-0f46-4f7a-883b-24628d2ce8df)

**Comment by jmk-randers** [comment]
Bekræftet, jeg er også Admin på prototypes og jeg får samme fejl:

![image](https://github.com/Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter/assets/80261692/a141aa92-905d-4dad-9d55-ec5a11f0e01e)

**Comment by jmk-randers** [comment]
@kf-randers : Fejlen er rettet ved leverandøren, tester du at det fungerer efter hensigten hos dig også? Det virker på min udviklermaskine...

Du kan lukke issuet med "Close with comment" når du har testet og bekræftet (i kommentaren) at det virker igen!
