### ISSUE TITLE
Klimamonitor indikator 7.1: Andel fossilfri busser

### ISSUE THREAD

**Issue by kf-randers** [Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter#75]

**Comment by kf-randers** [comment]
@hkl-randers ved du ikke noget om dette?

**Comment by hkl-randers** [comment]
Ja, det gør jeg. Vi kan måske bruge 6-by nøgletal med 2022-tal og 2020-tal.

**Comment by hkl-randers** [comment]
Jo :) Måske kan Nana Paulli Juul Andersen fra Veje og Trafik være vores kontaktperson

**Comment by hkl-randers** [comment]
Nu er data på open data dk :) drivmidler-for-busser-6by-nogletal

**Comment by hkl-randers** [comment]
@st-randers @rak-randers  Hej Søren og Rune. Vi har prøvet at lægge data op på busser, og vi får den her fejl. Kan I gennemskue, hvad der er galt?  

![Image](https://github.com/Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter/assets/142406647/25298647-476e-4c8b-a104-2a94149cd194)

**Comment by st-randers** [comment]
@hkl-randers 
Så skulle problemet gerne være løst på din branch. Jeg mangler stadig at merge, men der er nogle konflikter der skal løses manuelt - det skal jeg nok kigge på.

**Comment by st-randers** [comment]
Problemet er helt løst og data er tilgængelig på prototypes.

**Comment by hkl-randers** [comment]
Indikatorer lavet: 
- Andel fossilfrie by- og lokalbusser baseret på 6-by Nøgletal data, senest fra 2022. Vær dog obs på, at 6-By Nøgletal ikke længere udgives. Der kan evt. lave en rundspørge blandt kommunerne primo 2024, da der kun skal spørges om antallet af by- og lokalbusser fordelt på diesel, gas, hybrid og el. 

- Bussers brug af fossile brændstoffer (TJ) baseret på Planenergi. Skal opdateres manuelt i open data, når nye data kommer.
