### ISSUE TITLE
Brugerstyring

### ISSUE THREAD

**Issue by kf-randers** [Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter#81]
Camilla (CamillaOS) kan ikke tilføjes som Assignee på et issue. @jmk-randers kan du gennemskue hvad der er galt? Jeg kan heller ikke tilføje hende til projektet.

**Comment by kf-randers** [comment]
Problemet er vist blot, at kun skal tilføjes [Randers Kommunes team...](https://github.com/orgs/Randers-Kommune-Digitalisering/people)

**Comment by jmk-randers** [comment]
@kf-randers : Du kan lukke issuet med "Close with comment" når i har testet at det virker og hun har adgang til det hun skal have...

**Comment by kf-randers** [comment]
Det virker
