### ISSUE TITLE
Tests before merge

### ISSUE THREAD

**Issue by jmk-randers** [Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter#90]
1. Clone master and test-run in Node-RED IDE to create current DB format. Make sure data is pulled and written. (you might have to temporarily change request config to simulate a previous run)
2. Keeping the DB, Clone the branch with the changes in and try to run and check that values are updated in the database

**Comment by jmk-randers** [comment]
Master branch is currently broken and doesent write values.. Need to revert to an earlier commit to test if the DB changes work.

**Comment by jmk-randers** [comment]
@st-randers: Found non aligned data-columns... 

st-BIL-54 WRITES the data from the TID coloumn as RAW without converting. This change breaks the charts on the dashboard that expects a "Måned" column with an ISO8601 date...

**Comment by st-randers** [comment]
Remaining columns now renamed according to column_renaming object which contains raw data column names as keys, and their respective new names as values in https://github.com/Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter/commit/535a88a2b62795bc6c493517092f5c132d91c18e
